# Generated by Django 4.0.6 on 2022-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVideoClub', '0002_alter_pelicula_fechaalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fechaAlquiler',
            field=models.CharField(max_length=8),
        ),
    ]
