# Generated by Django 4.0.6 on 2022-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVideoClub', '0003_alter_pelicula_fechaalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fechaAlquiler',
            field=models.DateField(),
        ),
    ]
